language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.7

script:
  - sbt clean coverage test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - pip install --user codecov && codecov
  - ./upload_codacy_coverage.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
