language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.7

script:
  - sbt clean coverage test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - pip install --user codecov && codecov
  - curl -X POST https://api.codacy.com/2.0/coverage/$TRAVIS_COMMIT/scala -d `cat "target/scala-2.11/coverage-report/codacy-coverage.json"` --header "Content-Type: application/json" --header "project_token: $CODACY_PROJECT_TOKEN"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
